// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DotsController from "./dots_controller"
application.register("dots", DotsController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MapsController from "./maps_controller"
application.register("maps", MapsController)

import NewTaskController from "./new_task_controller"
application.register("new-task", NewTaskController)

import PlansController from "./plans_controller"
application.register("plans", PlansController)

import TaskFilterController from "./task_filter_controller"
application.register("task-filter", TaskFilterController)
